services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/takweemy
  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #     target: development
  #   command: yarn run start:dev auth
  #   env_file:
  #     - ./apps/auth/.env
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - .:/usr/src/takweemy
  # payments:
  #   build:
  #     context: .
  #     dockerfile: ./apps/payments/Dockerfile
  #     target: development
  #   command: yarn run start:dev payments
  #   env_file:
  #     - ./apps/payments/.env
  #   volumes:
  #     - .:/usr/src/takweemy
  # notifications:
  #   build:
  #     context: .
  #     dockerfile: ./apps/notifications/Dockerfile
  #     target: development
  #   command: yarn run start:dev notifications
  #   env_file:
  #     - ./apps/notifications/.env
  #   volumes:
  #     - .:/usr/src/takweemy
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
